metadata:
  name: ${project.artifactId}
  labels:
    group: ${project.groupId}
    project: ${project.artifactId}
    version: ${project.version}
    provider: jkube
    app: ${project.artifactId}
    expose: "true"
spec:
  ports:
    - name: http
      port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    app: ${project.artifactId}
    group: ${project.groupId}
    provider: jkube
